#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold)
  DIM=$(tput dim)
  RESET=$(tput sgr0)
  BLUE=$(tput setaf 4)
  GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3)
  RED=$(tput setaf 1)
else
  BOLD=""
  DIM=""
  RESET=""
  BLUE=""
  GREEN=""
  YELLOW=""
  RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say() { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  {
    if command -v wslview >/dev/null 2>&1; then
      wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then
      explorer.exe "$url"
    elif command -v xdg-open >/dev/null 2>&1; then
      xdg-open "$url"
    elif command -v open >/dev/null 2>&1; then
      open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" >"$tmp" || true
  printf '%s=%s\n' "$key" "$value" >>"$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  ((${#WRITTEN_ENV[@]})) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  ((${#WRITTEN_SECRET[@]})) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if ((${#SKIPPED[@]})); then
    printf '\n'
    warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "create-agent-stack release setup"

stage "Connect the GitHub repository"
say "The release workflow needs this local repository connected to GitHub."
if GITHUB_REPOSITORY_URL=$(git remote get-url origin 2>/dev/null); then
  note "origin already points to: $GITHUB_REPOSITORY_URL"
else
  open_url "https://github.com/new"
  step "Create a repository named agent-stack; do not initialize it with a README, license, or .gitignore."
  step "On the repository's Quick Setup page, copy its HTTPS URL ending in .git."
  ask GITHUB_REPOSITORY_URL "Paste the GitHub repository URL:"
  if [[ "$GITHUB_REPOSITORY_URL" != https://github.com/*/*.git ]]; then
    warn "expected an HTTPS GitHub URL such as https://github.com/OWNER/agent-stack.git"
    exit 1
  fi
  git remote add origin "$GITHUB_REPOSITORY_URL"
  say "✓ added Git remote origin"
fi

REPOSITORY_SLUG=${GITHUB_REPOSITORY_URL#https://github.com/}
REPOSITORY_SLUG=${REPOSITORY_SLUG%.git}
if [[ "$REPOSITORY_SLUG" == "$GITHUB_REPOSITORY_URL" || "$REPOSITORY_SLUG" != */* ]]; then
  warn "origin must use an HTTPS GitHub URL before this wizard can continue"
  exit 1
fi

if git rev-parse --verify HEAD >/dev/null 2>&1; then
  if confirm "Rename the current branch to main and push it to origin now?"; then
    git branch -M main
    git push -u origin main
    say "✓ pushed main to GitHub"
  else
    SKIPPED+=("push main to origin")
  fi
else
  SKIPPED+=("create the first commit, then push main to origin")
  warn "this repository has no commit yet, so the wizard cannot push main"
fi
pause "Press Enter to continue"

stage "Enable GitHub Actions permissions"
say "Release Please needs permission to update release metadata and open its release pull request."
open_url "https://github.com/${REPOSITORY_SLUG}/settings/actions"
step "Scroll to Workflow permissions."
step "Select Read and write permissions."
step "Enable Allow GitHub Actions to create and approve pull requests."
step "Select Save."
pause "Press Enter after GitHub confirms the settings were saved"

stage "Create the npm publication token"
say "The unpublished package needs a temporary CI token for its first automated publication."
printf '  %s⚠ %s%s\n' "$RED" "Because @tiagojacinto/create-agent-stack does not exist on npm yet, package-specific restriction may not be available. Use the shortest practical expiration and rotate to npm trusted publishing after the first release." "$RESET"
open_url "https://www.npmjs.com/settings/~/tokens"
step "Select Generate New Token, then choose Granular Access Token."
step "Name it tiagojacinto-create-agent-stack-github-actions and choose the shortest expiration you can maintain."
step "Under Packages and scopes, grant Read and write access. If the unpublished package cannot be selected, choose All packages temporarily."
step "Enable Bypass two-factor authentication only because GitHub Actions must publish unattended."
step "Generate the token and copy it now; npm will not show it again."
ask_secret NPM_TOKEN "Paste the npm token:"
if [[ -z "$NPM_TOKEN" ]]; then
  warn "an npm token is required"
  exit 1
fi
set_secret NPM_TOKEN "$NPM_TOKEN"
if [[ ! " ${WRITTEN_SECRET[*]} " =~ " NPM_TOKEN " ]]; then
  open_url "https://github.com/${REPOSITORY_SLUG}/settings/secrets/actions/new"
  step "Set the secret name to NPM_TOKEN and paste the token as its value, then select Add secret."
  pause "Press Enter after GitHub confirms the secret was added"
fi

stage "Verify release readiness"
say "This stage checks configuration without creating a release."
if [[ -f .github/workflows/release.yml ]]; then
  say "✓ release workflow exists"
else
  warn "missing .github/workflows/release.yml"
  exit 1
fi
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if gh secret list | grep -q '^NPM_TOKEN'; then
    say "✓ GitHub secret NPM_TOKEN exists"
  else
    warn "GitHub secret NPM_TOKEN was not found"
    SKIPPED+=("verify GitHub secret NPM_TOKEN")
  fi
else
  SKIPPED+=("verify GitHub workflow and secret with gh")
  warn "gh is unavailable or unauthenticated, so remote verification was skipped"
fi
if confirm "Run the complete local release gate now? It takes about 3 minutes."; then
  bun run check
else
  SKIPPED+=("run bun run check")
fi
say "A future fix:, feat:, or breaking Conventional Commit on main will create or update the release pull request."
say "Merging that release pull request creates the GitHub release and publishes the npm package."
pause "Press Enter to finish"

finish
