import { minimumSelection } from "./catalog.js";

export function minimumProjectFiles(projectName: string): Readonly<Record<string, string>> {
  return {
    "package.json": json({
      name: projectName,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        dev: "tsx watch src/index.ts",
        build: "tsc -p tsconfig.build.json",
        format: "oxfmt .",
        "format:check": "oxfmt --check .",
        lint: "oxlint .",
        typecheck: "tsc --noEmit",
        test: "vitest run",
        check: "pnpm format:check && pnpm lint && pnpm typecheck && pnpm test",
      },
      engines: { node: ">=22" },
      packageManager: "pnpm@10.11.0",
      devDependencies: {
        "@types/node": "^22.15.30",
        oxfmt: "^0.16.0",
        oxlint: "^1.2.0",
        tsx: "^4.20.3",
        typescript: "^5.8.3",
        vitest: "^3.2.2",
      },
    }),
    "tsconfig.json": json({
      compilerOptions: {
        target: "ES2023",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        strict: true,
        noUncheckedIndexedAccess: true,
        exactOptionalPropertyTypes: true,
        verbatimModuleSyntax: true,
        types: ["node", "vitest/globals"],
        skipLibCheck: true,
      },
      include: ["src/**/*.ts", "tests/**/*.ts"],
    }),
    "tsconfig.build.json": json({
      extends: "./tsconfig.json",
      compilerOptions: {
        outDir: "dist",
        rootDir: "src",
        declaration: true,
        sourceMap: true,
        types: ["node"],
      },
      include: ["src/**/*.ts"],
    }),
    "vitest.config.ts": text`
      import { defineConfig } from "vitest/config";

      export default defineConfig({
        test: {
          include: ["tests/**/*.test.ts"],
        },
      });
    `,
    "src/index.ts": text`
      export function greet(name: string): string {
        const normalizedName = name.trim();
        if (normalizedName.length === 0) {
          throw new Error("A non-empty name is required to create a greeting.");
        }
        return \`Hello, \${normalizedName}!\`;
      }

      if (process.argv[1]?.endsWith("index.ts") || process.argv[1]?.endsWith("index.js")) {
        process.stdout.write(\`\${greet("agent")}\\n\`);
      }
    `,
    "tests/index.test.ts": text`
      import { describe, expect, it } from "vitest";

      import { greet } from "../src/index.js";

      describe("greet", () => {
        it("creates a greeting for a named recipient", () => {
          expect(
            greet("developer"),
            "Expected greet(name) to preserve the supplied recipient in the greeting.",
          ).toBe("Hello, developer!");
        });

        it("explains why an empty recipient is invalid", () => {
          expect(() => greet("   ")).toThrow("A non-empty name is required to create a greeting.");
        });
      });
    `,
    ".github/workflows/ci.yml": text`
      name: CI

      on:
        pull_request:
        push:
          branches: [main]

      permissions:
        contents: read

      jobs:
        verify:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: pnpm/action-setup@v4
              with:
                version: 10.11.0
            - uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: pnpm
            - run: pnpm install --frozen-lockfile
            - run: pnpm check
            - run: pnpm audit --audit-level high
            - uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
    `,
    ".gitleaks.toml": text`
      title = "${projectName} gitleaks configuration"

      [extend]
      useDefault = true
    `,
    ".gitignore": text`
      node_modules/
      dist/
      coverage/
      .DS_Store
    `,
    "README.md": text`
      # ${projectName}

      This project was generated by create-agent-stack with the Minimum preset.

      ## Requirements

      - Node.js 22 or newer
      - pnpm 10.11.0

      ## Commands

      - \`pnpm dev\` — run the entry point in watch mode.
      - \`pnpm build\` — compile production output.
      - \`pnpm test\` — run unit tests.
      - \`pnpm check\` — run formatting, linting, type checking, and tests.

      GitHub Actions additionally runs dependency auditing and gitleaks secret scanning.
      Add capabilities progressively; record each addition in \`.agent-stack/manifest.json\`.
    `,
    "AGENTS.md": text`
      # Agent instructions

      1. Read \`README.md\`, \`docs/GLOSSARY.md\`, and \`.agent-stack/progress.json\` before changing code.
      2. Work on one feature at a time and leave the repository in a passing state.
      3. Run \`pnpm check\` before declaring work complete.
      4. Update documentation and progress records when behavior, boundaries, or invariants change.
      5. Never weaken or remove a failing check merely to make it pass.
    `,
    "docs/GLOSSARY.md": text`
      # Glossary

      - **Agent stack:** The selected tools and project artifacts that constrain and guide coding agents.
      - **Feature:** One independently verifiable capability installed by the scaffolder.
      - **Minimum preset:** The smallest supported set of correctness, maintainability, security, and context features.
      - **Project check:** The aggregate \`pnpm check\` command that must pass before work is complete.
      - **Progress manifest:** The structured record used to continue work across agent sessions.
    `,
    ".agent-stack/manifest.json": json({
      schemaVersion: 1,
      preset: minimumSelection.preset,
      features: minimumSelection.features,
    }),
    ".agent-stack/progress.json": json({
      schemaVersion: 1,
      currentMilestone: "minimum-project-generated",
      completed: ["minimum-project-generated"],
      next: "Define the first product feature before adding implementation code.",
    }),
  };
}

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function text(strings: TemplateStringsArray, ...values: readonly unknown[]): string {
  const raw = String.raw({ raw: strings }, ...values);
  const lines = raw.replace(/^\n/, "").split("\n");
  const indentation = Math.min(
    ...lines
      .filter((line) => line.trim().length > 0)
      .map((line) => line.match(/^\s*/)?.[0].length ?? 0),
  );
  return `${lines
    .map((line) => line.slice(indentation))
    .join("\n")
    .trimEnd()}\n`;
}
